version: "3.7"
services:
    db:
        image: "mysql:backoffice"
        volumes:
            - db_data:/var/lib/mysql
        environment: 
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_DATABASE: Backoffice
        ports:
          - 3306:3306     
volumes:
  db_data:
